### ISSUE TITLE
this repository contains a virus

### ISSUE THREAD

**Issue by GassaFM** [YuryBandarchuk16/CodeforcesSurfer#3]
The file `.idea/description.html` most probably contains a virus.
Verified by [virustotal.com](https://www.virustotal.com/en/file/e4d81f4aca7d1b9b5cebc29baf9682cb7d8435b87e955b924e249f7e7045c8ab/analysis/) (43/51 detection ratio).
Putting it here as other ways of communication with the repository author have failed.

**Comment by YuryBandarchuk16** [comment]
Ooops, I am so sorry 
That's because of my old PC. It doesn't contain an AV.

Sorry again.
